### PR TITLE
Update `won` in chapter12/source.rkt

### PR DESCRIPTION
**Pull request by r5d**
Add additional check to see if AI won the game and if so, return
"AI won."

### CODE REVIEW

**Comment by samth** [comment]
@mfelleisen Is this ok to merge?

**Comment by mfelleisen** [comment]
No. I just realized that (stupid me) that someone turned this thing into a package. 
We had agreed that we leave this in collects because Realm readers are likely to 
be inexperienced people who can't find their way around package systems easily.

**Comment by samth** [comment]
The discussion in 2013 ended with us putting a text file in `collects/realm` pointing to the correct location.

**Comment by mfelleisen** [comment]
Yes I noticed the text file now. 

Matthew and I had agreed to a special provision for Realm. I don't recall being asked about this.

**Comment by mflatt** [comment]
I'm pretty sure Sam remembers correctly, and we agreed on a "README.txt". (The commit to add "README.txt" is by me in 2013.)

**Pull request merged**
